version: 0.1
os: linux

files:
  - source: /
    destination: /var/www/html


hooks:

  ApplicationStop:
    - location: scripts/stopServer.sh
  BeforeInstall:
    - location: scripts/serverPermission.sh 

  ApplicationStart:
    - location: scripts/startServer.sh

