version: 0.2
env:
  variables:
    db: ""
phases:
  pre_build:
    commands:
      - sudo apt update
      - sudo apt install jq -y
      - DB_NAME=$(aws ssm get-parameters --name /aryan/db_name  --query "Parameters[0]" | jq -r .Value)
      - DB_USER=$(aws ssm get-parameters --name /aryan/db_user  --query "Parameters[0]" | jq -r .Value)
      - DB_PASSWD=$(aws ssm get-parameters --name /aryan/db_password --with-decryption --query "Parameters[0]" | jq -r .Value)
      - DB_HOST=$(aws ssm get-parameters --name /aryan/db_host  --query "Parameters[0]" | jq -r .Value)
      - sudo sed -i 's/database_name_here/'$DB_NAME'/' wp-config.php
      - sudo sed -i 's/username_here/'$DB_USER'/' wp-config.php
      - sudo sed -i 's/password_here/'$DB_PASSWD'/' wp-config.php
      - sudo sed -i 's/localhost/'$DB_HOST'/' wp-config.php

  build:
    commands:
      - echo Build Completed on `date`
  post_build:
    commands:
      - echo Congratulations!!!!!
      - cat wp-config.php


artifacts:
  files:
    - '**/*'
